languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Valentine Samuel"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Valentine Samuel Software Engineer Portfolio and Blog"

[params.author]
  name = "Valentine Samuel"
  image = "img/hello.png"
  headline = "Software Engineer"
  bio = "I love to build systems that scale"
  links = [
    { email = "mailto:valentinesamuel2580@gmail.com" },
    { github = "https://github.com/valentinesamuel" },
    { linkedin = "https://www.linkedin.com/in/samuel-val/" }
  ]
